title: Demo title
description: Demo description
author: Demo author
urlRoot: /
sites:
  barusu:
    urlRoot: /barusu
    dataRoot: barusu/data
    sourceRoot: barusu/source
    assetDataMapFilepath: asset.map.json
    tagDataMapFilepath: tag.map.json
    categoryDataMapFilepath: category.map.json
    source:
      image:
        dataRoot: image
        sourceRoot: .
        pattern:
          - '**/*{.png,jpg}'

deploy:
  type: git
  branch: master
  repository:
  name:
  email:
